### ISSUE TITLE
Automate CPT restart fix when replica exchange is on

### ISSUE THREAD

**Issue by hgandhi2411** [ur-whitelab/peptidesim#1]
Currently, peptidesim cannot restart automatically in case the simulation stops for any reason. 
In case of a job timeout, peptidesim throws an error while restarting if the cpt files for all replicas are not at the same timestep. Writing the cpt file takes a long time and if jobs timeout while cpt files are being updated, the update may be incomplete causing a mismatch between cpts for different replicas.

**Comment by hgandhi2411** [comment]
This issue seems to be solved with the multidir flag. I ran tests where cpt files were created very frequently for longer simulations, then interrupted and restarted the simulation.

**Comment by whitead** [comment]
Great! Thanks for testing. We'll re-open if we observe this issue again.
