### ISSUE TITLE
Changing gromacs generated PDB chains to work for plumed 

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/peptidesim#11]

**Comment by hgandhi2411** [comment]
If our system contains 4 copies of 'GED' peptide and 5 copies of 'KIM' peptide, the gromacs pdb has chain identifiers as A,B,A,B for the 4 'GED' chains and C,D,C,D,C for the 5 'KIM' chains. 
When using plumed for enhanced sampling, each peptide chain in the system must have a unique identifier in the input pdb. So, we need to add a functionality to change the chain identifiers in the pdb when using plumed.
