### ISSUE TITLE
Remove files when removing items from pickle object

### ISSUE THREAD

**Issue by whitead** [ur-whitelab/peptidesim#5]

**Comment by hgandhi2411** [comment]
The ps.remove() function removes items from pickle object but not the actual files in the file system. Deleting the files from the file system will ensure that extra memory is not used up by the simulation since gromacs, by default, backs up existing files when rerunning the simulation.

**Comment by whitead** [comment]
Note: Maybe just add test case for error sim failure which was the only use-case for this.

**Comment by whitead** [comment]
Based on discussion, we'll move simulation directory (e.g., `[original-name]-backup-0`). There is already test-code written, just add a check for ensuring the directory of the simulation has disappeared.

**Comment by whitead** [comment]
Addressed by #75
