### ISSUE TITLE
Remove files created from tests

### ISSUE THREAD

**Issue by hgandhi2411** [ur-whitelab/peptidesim#52]
The tests create many files and folders. Maybe we can use the setup/teardown like in htf to clean these up after the tests are done.

**Comment by whitead** [comment]
They should all be removed with the current tests. They are only not removed if the tests fails. Please let me know though if a particular test is not doing this.

**Comment by hgandhi2411** [comment]
You are right, the tests clean up after themselves when they pass.

**Comment by hgandhi2411** [comment]
`test_remove_restart` didn't clean up the files.

**Comment by hgandhi2411** [comment]
resolved by #53
