### ISSUE TITLE
Handle multiple peptide sequences well

### ISSUE THREAD

**Issue by hgandhi2411** [ur-whitelab/peptidesim#55]
The `Bio.SeqUtils.ProtParam.ProteinAnalysis` class used in `_pdb_file_generator` cannot handle a list of sequences. So, the initialization fails when using more than one sequence. We either need to fix the way this function works or think of a better way to take in multiple sequences.

**Comment by hgandhi2411** [comment]
Here's the error I get when trying to use two sequences:
```
Traceback (most recent call last):
  File "part_1.py", line 37, in <module>
    ps.initialize()
  File "/gpfs/fs2/scratch/hgandhi/peptidesim/package/peptidesim/peptidesim.py", line 498, in initialize
    s, 'seq_' + str(i))
  File "/gpfs/fs2/scratch/hgandhi/peptidesim/package/peptidesim/peptidesim.py", line 1034, in _pdb_file_generator
    p = ProteinAnalysis(sequence)
  File "/home/hgandhi/.local/lib/python3.7/site-packages/Bio/SeqUtils/ProtParam.py", line 78, in __init__
    if prot_sequence.islower():
AttributeError: 'list' object has no attribute 'islower'
```

**Comment by hgandhi2411** [comment]
@whitead all the tests pass but when I launch jobs, I get the above error. I looked at biopython docs and seems like `ProteinAnalysis()` can take in only one string, I don't know how it worked earlier.

**Comment by whitead** [comment]
Not sure, can you fix it?

**Comment by hgandhi2411** [comment]
Okay, figured out. This has to do with the way we define sequences in the input file. In the most recent input file, the seq is turned into a list while making the peptidesim object. 
For my simulation, I was giving in a list of sequences in my bash script and when the input file converted that to a list, the input to `ProteinAnalysis()` became a list of list (example `[['AA', 'EE']]`) which caused this issue. As long as the sequence input is not a nested list, peptidesim works fine.
