### ISSUE TITLE
Grompp error on restart if previous pickle files are not deleted

### ISSUE THREAD

**Issue by hgandhi2411** [ur-whitelab/peptidesim#60]
Someone other than me should check if they can restart simulations smoothly without deleting previous pickle files.

**Comment by whitead** [comment]
@hgandhi2411 can you provide a few more details? Did you have to delete the pickle file corresponding the simulation or just all previous?

**Comment by hgandhi2411** [comment]
I had to delete all the outdated pickle files. For example, if I restarted 3 times, there were 3 sets of pickle files that were generated. I had to keep the latest set and delete the rest.
